import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#221f1a",
        "on-secondary": "#3a2f1f",
        "background-light": "#FFFCFC",
        "on-primary": "#3e2e00",
        "text-muted-dark": "#737373",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#394473",
        "on-secondary-container": "#c7b6a0",
        "secondary-fixed": "#f3e0c8",
        "background": "#16130e",
        "surface-variant": "#38342e",
        "on-primary-fixed-variant": "#5a4400",
        "on-background": "#e9e1d8",
        "outline-variant": "#4d4639",
        "on-primary-container": "#523e00",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#514534",
        "tertiary-fixed": "#dde1ff",
        "on-tertiary-container": "#323e6c",
        "tertiary": "#bac5fd",
        "on-primary-fixed": "#251a00",
        "on-surface-variant": "#d0c5b4",
        "surface-container-high": "#2d2a24",
        "surface-tint": "#e4c375",
        "outline": "#999080",
        "inverse-surface": "#e9e1d8",
        "tertiary-container": "#9faae0",
        "surface-container-lowest": "#100e09",
        "secondary": "#d6c4ad",
        "text-muted-light": "#A6A8A1",
        "secondary-container": "#544736",
        "secondary-fixed-dim": "#d6c4ad",
        "on-secondary-fixed": "#231a0c",
        "surface-container-highest": "#38342e",
        "on-tertiary": "#222d5b",
        "surface-dim": "#16130e",
        "surface-bright": "#3c3932",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#e4c375",
        "primary": "#e5c476",
        "primary-container": "#c8a95e",
        "surface-container-low": "#1e1b16",
        "inverse-on-surface": "#33302a",
        "tertiary-fixed-dim": "#b9c4fb",
        "on-tertiary-fixed": "#0a1745",
        "surface": "#16130e",
        "inverse-primary": "#745b17",
        "on-error": "#690005",
        "on-surface": "#e9e1d8",
        "background-dark": "#000000"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        md: "16px",
        "margin-mobile": "16px",
        xxl: "80px",
        sm: "8px",
        lg: "24px",
        unit: "4px",
        gutter: "24px",
        "margin-desktop": "64px",
        xs: "4px",
        xl: "40px"
      },
      fontFamily: {
        labelSm: ["Inter"],
        headlineMd: ["Libre Caslon Text"],
        headlineLg: ["Libre Caslon Text"],
        displayLg: ["Libre Caslon Text"],
        bodyLg: ["Inter"],
        displayLgMobile: ["Libre Caslon Text"],
        labelMd: ["Inter"],
        bodyMd: ["Inter"],
        mono: ["JetBrains Mono"]
      },
      fontSize: {
        labelSm: ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        headlineMd: ["24px", { lineHeight: "32px", fontWeight: "400" }],
        headlineLg: ["32px", { lineHeight: "40px", fontWeight: "400" }],
        displayLg: ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "400" }],
        bodyLg: ["18px", { lineHeight: "28px", fontWeight: "400" }],
        displayLgMobile: ["40px", { lineHeight: "48px", fontWeight: "400" }],
        labelMd: ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        bodyMd: ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
};
export default config;
